/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimsIdRouteImport } from './routes/claims.$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIdRoute = ClaimsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClaimsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRouteWithChildren
  '/new': typeof NewRoute
  '/claims/$id': typeof ClaimsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRouteWithChildren
  '/new': typeof NewRoute
  '/claims/$id': typeof ClaimsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims': typeof ClaimsRouteWithChildren
  '/new': typeof NewRoute
  '/claims/$id': typeof ClaimsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/claims' | '/new' | '/claims/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claims' | '/new' | '/claims/$id'
  id: '__root__' | '/' | '/claims' | '/new' | '/claims/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsRoute: typeof ClaimsRouteWithChildren
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/$id': {
      id: '/claims/$id'
      path: '/$id'
      fullPath: '/claims/$id'
      preLoaderRoute: typeof ClaimsIdRouteImport
      parentRoute: typeof ClaimsRoute
    }
  }
}

interface ClaimsRouteChildren {
  ClaimsIdRoute: typeof ClaimsIdRoute
}

const ClaimsRouteChildren: ClaimsRouteChildren = {
  ClaimsIdRoute: ClaimsIdRoute,
}

const ClaimsRouteWithChildren =
  ClaimsRoute._addFileChildren(ClaimsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsRoute: ClaimsRouteWithChildren,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
